[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
platform_packages =
    framework-arduino-pico @ https://github.com/earlephilhower/arduino-pico.git
monitor_speed = 115200
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
lib_deps =
    BTstackLib
    adafruit/Adafruit NeoPixel
    SD